### ISSUE TITLE
Create and distribute a RPM package for vale and the Red Hat style.

### ISSUE THREAD

**Issue by themr0c** [redhat-documentation/vale-at-red-hat#117]
For an easier onboarding on Fedora and RHEL, a `vale` and a `vale-style-red-hat` RPM package would be nice.

Even better is they are listed there: https://repology.org/project/vale/versions

**Comment by alexpdp7** [comment]
The upstream docs site has been updated with a COPR maintained by someone in my team :)

**Comment by rolfedh** [comment]
> The upstream docs site has been updated with a COPR maintained by someone in my team :)

https://vale.sh/docs/vale-cli/installation/
