### ISSUE TITLE
RedHat.Usage: The message for the RedHat.Usage rule is too vague

### ISSUE THREAD

**Issue by themr0c** [redhat-documentation/vale-at-red-hat#141]
* When possible, create more specific rules (Example: https://github.com/Vale-at-Red-Hat/vale-at-red-hat/blob/main/.vale/styles/RedHat/As.yml).
* Propose a better message than: "Verify your use of '%s' with the word usage guidelines."
* Propose a better link than this obsolete link: "https://www.ibm.com/developerworks/library/styleguidelines/index.html#wordlist"
* More generally, it would be preferable to find a preferred word and move the words to `TermsErrors`, `TermsWarnings` or `TermsSuggestions`.

**Comment by aireilly** [comment]
Fixed in https://github.com/redhat-documentation/vale-at-red-hat/pull/585
