### ISSUE TITLE
vale errors on hostname, TLS, terminal, OS, vscode

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/vale-at-red-hat#145]
**Describe the bug**
The following words or expressions trigger illegitimate vale alerts:

**1.** 
We need `hostname` as per IMB Style on p. 292:
![image](https://user-images.githubusercontent.com/78564304/148204387-3437ea35-c36d-4d29-9536-8316b9326739.png)
**I suggest downgrading this rule to a warning to avoid massive fixes of `host name` to older docs and to allow for use of `hostname` in new docs.**

**2.**
The following screenshot is self-explanatory--the lintered text is **`SSL TLS`**:
![image](https://user-images.githubusercontent.com/78564304/148206878-ffeb120c-0d36-4989-a613-f310948f9351.png)
How it happened:
At first I had just `TLS` in the text: this was blocked by Vale as an error.
So I changed it to `SSL TLS`: :smile: now I got two errors, one for `SSL` (Vale doesn't see TLS with it) and one for `TLS` (Vale doesn't see SSL with it).
In my docs, only TLS is mentioned. If I have to add SSL, that may be technically incorrect:
https://www.internetsociety.org/deploy360/tls/basics/
https://www.ssl.com/faqs/faq-what-is-ssl/
**I suggest removing this rule also because SSL and TLS don't seem to be the same thing and in many situations only one of them should be mentioned.**

**3.**
![image](https://user-images.githubusercontent.com/78564304/148204632-f7a229e3-80ab-4710-9e5e-a0234bae0ff2.png)
The above rule prevents me from using phrases like "in the terminal window". I can live with having to use `shell prompt`, if I'm forced to do so by Vale, to describe how to enter a command; however, in other situations, like when asking the user to (for example) verify the output of a command in the terminal window, the meaning doesn't work with `shell prompt` (or even with `command line`). So based on my experience, `shell prompt` and `terminal` are not interchangeable (and by extension also `terminal window` because then I can't write even `terminal window` as Vale will block it as an error due to `terminal` in it).
Please also note that IMB Style does not prohibit use of the word `terminal`, as can be seen on p. 347: 
![image](https://user-images.githubusercontent.com/78564304/148205013-a537063b-d2b0-4b6c-9fa3-aca624983687.png)
**I suggest downgrading this rule to a warning as explained.**

**4.**
![image](https://user-images.githubusercontent.com/78564304/148253250-95e3877b-7124-4d9e-a6c9-1d1a9554ce7d.png)
As the screenshot above shows, we cannot always replace `OS` with `operating system`. There are product names that have `OS` in them like [macOS](https://www.apple.com/macos/) and `z/OS` as in :https://www.eclipse.org/che/docs/che-7/extensions/eclipse-che4z/ and in https://github.com/eclipse/che-docs/pull/2204/
**I suggest downgrading this rule to a warning as explained.**

**5.**
![image](https://user-images.githubusercontent.com/78564304/148248883-80f08902-76d8-4408-95b7-00c6aef63a62.png)
Lower-case `vscode` should be acceptable because of its occurrences in third-party links.
**I suggest downgrading this rule to a warning as explained.**

**Comment by themr0c** [comment]
Thanks for the report! To work on that, we will have to split into 5 distinct issues.

**Comment by themr0c** [comment]
Please add point 3. to #114.

**Comment by themr0c** [comment]
For 2., see #147

**Comment by themr0c** [comment]
4. is a good candidate for scoping. Disable a rule that is irrelevant in the file context. See https://redhat-documentation.github.io/vale-at-red-hat/docs/end-user-guide/defining-a-vale-onboarding-strategy/#_fix_the_alerts

**Comment by themr0c** [comment]
5. is a good candidate for scoping too. Disable a rule that is irrelevant in the file context. See redhat-documentation.github.io/vale-at-red-hat/docs/end-user-guide/defining-a-vale-onboarding-strategy/#_fix_the_alerts

**Comment by themr0c** [comment]
For 1.: Indeed, SSG removed the entry for "host name".  See: https://github.com/redhat-documentation/supplementary-style-guide/pull/114

**Comment by themr0c** [comment]
1. 2. 3. are done
4. and 5. are candidates for exceptional treatment in scoping rules.
I believe we are good.

**Comment by themr0c** [comment]
Implemented with #164
