### ISSUE TITLE
Would it help to create a sub-style for the OpenShift Documentation guidelines

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#146]
**Is your feature request related to a problem? Describe.**
The following OpenShift Documentation guidelines are widely used, and include many style rules that are not covered elsewhere. For example, see
https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#object-references

**Describe the solution you'd propose**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots here.

**Comment by themr0c** [comment]
Yes, let's create a new repository using https://github.com/Vale-at-Red-Hat/CheDocs as a template.

**Comment by rolfedh** [comment]
FYI - Closing this issue as obsolete.
It looks like the OpenShift docs team has made some customizations but hasn't chosen to create it's own Style, yet. These customizations include items such as:
- An `openshift-docs/.vale/styles/Vocab/OpenShiftDocs` directory and a corresponding entry in their `.vale.ini file` .
- A `vale-at-red-hat/tree/main/.vale/styles/OpenShiftAsciiDoc` style.
