### ISSUE TITLE
Vale is not smart enough to correctly process a combination of two rules

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/vale-at-red-hat#158]
**Describe the bug**
If Git should be capitalized, its (and any other product name capitalization) should not be lowercase because of sentence-style capitalization of headings:
![image](https://user-images.githubusercontent.com/78564304/150518857-66620243-3fce-4890-a963-b7960a0cd1b3.png)

**Comment by boczkowska** [comment]
The capitalization rule can be modified with the `exceptions` option. See https://github.com/errata-ai/vale/issues/299
I can take a look at it if nobody works on it.

**Comment by themr0c** [comment]
Silently implemented with #164. I apologize, @boczkowska. But there are also other nice issues!
