### ISSUE TITLE
Red Hat/CCS sponsorship for the Vale project

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#181]
**Is your feature request related to a problem? Describe.**

The open-source Vale software is central to the Vale at Red Hat project. We would like to reciprocate and support the Vale project by making a financial contribution through https://opencollective.com/vale  

**Describe the solution you'd propose**

* Re-submit Vale as a proposal to Ruth Suehle (rsuehle), Director of Community Outreach, who posts a form for nominations each December.

**Describe alternatives you've considered**

* We need to explore what alternatives are available.

**Additional context**

Thread in CoreOS's #vale-at-red-hat channel: https://coreos.slack.com/archives/C0218RXJK5E/p1644441075194029

**Comment by rolfedh** [comment]
FYI @aireilly

**Comment by aireilly** [comment]
I have A question out with Ruth. Let's see how she reponds.

**Comment by rolfedh** [comment]
@aireilly Would you like to handle this task and/or get others involved?

**Comment by aireilly** [comment]
We missed this round, unfortunately. The next round will be Oct/Nov 2022 :(

**Comment by rolfedh** [comment]
No problem, Aidan.
How do we set the stage for success, in advance of the Oct/Nov date?
- Can we file now for that Oct/Nov funding? Or when do they start accepting applications?
- Does it help if the application has many petitioners, a sponsor, or is a single applicant enough?

**Comment by aireilly** [comment]
We should look into this again 👀

**Comment by rolfedh** [comment]
As the creator of this issue and after reviewing our current priorities, I notice this issue has become stale without recent activity. I'm closing it for now. If it's still relevant or needs attention, please feel free to reopen it with new information. Thanks for your understanding.
