### ISSUE TITLE
Build should not fail on linting errors

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#185]
These should not be registered as errors in a PR build: 
* Linting with Vale on pull request (pull_request)
* Linting with Vale on push / Linting with Vale on push (push)

**Comment by themr0c** [comment]
I disagree. Current behavior is fine, and is exactly what we want to promote: do not accept incoming changes that are causing linter errors.

**Comment by aireilly** [comment]
Makes sense. I would like to see the errors dramatically reduced in the repo if possible. We should aim for zero errors as best practice! I added this PR to begin with: https://github.com/redhat-documentation/vale-at-red-hat/pull/202
