### ISSUE TITLE
Document how to configure Vale CLI with Atom 

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#192]
We need to document how to configure Vale CLI with Atom in the VaRH docs. This is a good start: https://docs.engineering.redhat.com/display/TELCODOCS/Installing+and+using+Vale+on+Atom+editor

**Comment by michelle-purcell** [comment]
+1 and #me_to to this issue. I cannot get the vale-at-red-hat linter integrated with Atom. 

I successfully installed vale and vale-at-red-hat on the CLI and that works fine. I cannot get the integration working in the Atom editor. Nothing happens after installing the pre-req packages in Atom and configuring the path to vale.

I would be happy to test and contribute to any documentation that gets created to resolve this issue. Thanks :-)

**Comment by themr0c** [comment]
Atom sunsetting soon, it's not a priority.
