### ISSUE TITLE
"on-premise" is incorrectly marked as an error

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/vale-at-red-hat#198]
**Describe the bug**
Vale currently reports "on-premise" as incorrect, and that it should be replaced with "on-premises" or another option.

Per the CCS supplementary style guide (and general Red Hat stance), "on-premise" is correct: https://redhat-documentation.github.io/supplementary-style-guide/#on-premise

Can we remove this rule? Or preferably flip it so that "on-premises" is marked as incorrect, with "on-premise" or "on-site" as the alternatives?

**To Reproduce**
Run vale against a file that contains the term "on-premise".

**Expected behavior**
No error is reported.

**Comment by themr0c** [comment]
And even, report it as a warning ("Use it: with caution")
