### ISSUE TITLE
Use 'AMD64' rather than 'x86_64' (RedHat.TermsErrors)

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/vale-at-red-hat#199]
**Describe the bug**

This word or expression triggers an illegitimate vale alert:
**error  Use 'AMD64' rather than         RedHat.TermsErrors 
               'x86_64'.** 

I recommend removing this rule for the following reasons:

`x86_64` and `AMD64` are not interchangeable. `x86_64` covers both `Intel 64` and `AMD64`. To rewrite `x86_64` as `AMD64` means telling readers (including those that use `Intel 64` for Red Hat products) that `Intel 64` does not exist and is not supported. (In other words, with this rule Vale tells us that `car` is an error and that we must replace `car` with `BMW`.)

OpenShift docs (and many, many package names for Linux distros) refer to `x86_64`: https://docs.openshift.com/container-platform/4.10/installing/installing-preparing.html

More info below:
https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures#64-bit_(x86-64)
https://en.wikipedia.org/wiki/X86
https://www.pcmag.com/encyclopedia/term/x64
https://www.intel.com/content/www/us/en/architecture-and-technology/microarchitecture/intel-64-architecture-general.html
https://www.pcmag.com/encyclopedia/term/amd64 (edited) 

![image](https://user-images.githubusercontent.com/78564304/158636550-13da6904-40a1-4173-b81c-0d7eda79ebdf.png)
(source: https://www.intel.com/content/www/us/en/architecture-and-technology/microarchitecture/intel-64-architecture-general.html)

`Intel 64` is explicitly supported on RHEL:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_installation/installing-rhel-on-adm64-intel-64-and-64-bit-arm
`x86_64` overall is supported on Fedora:
https://getfedora.org/en/coreos?stream=stable

**Comment by max-cx** [comment]
I've opened a SSG issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/171

**Comment by rohennes** [comment]
@themr0c - Hi Fabrice, were you looking for somebody to work on removing this from our list of terms (as a good newbie task!). I can open a PR next week for that if that works?

**Comment by themr0c** [comment]
That would be awesome!

**Comment by rohennes** [comment]
I touched base with Max. He thinks we should wait until the style council finalizes their decision before updating rule in Vale. Max is chasing it up with the style council

**Comment by rohennes** [comment]
From [Kelly Brown](https://github.com/redhat-documentation/supplementary-style-guide/issues/171#issuecomment-1306027435): "Myself and some SMEs from multi-arch and arm are working on a best practices guide on the use cases for both x86_64 vs amd64 and arm64 vs aarch64"

**Comment by rohennes** [comment]
This rule is being downgraded to a suggestion in #466. We can perhaps fine-tune further after we see the details in the related SSG issue.

**Comment by aireilly** [comment]
We should update the current Vale rules based on the following:
https://redhat-documentation.github.io/supplementary-style-guide/#amd64
https://redhat-documentation.github.io/supplementary-style-guide/#bit-64-x86
https://redhat-documentation.github.io/supplementary-style-guide/#bit-64-arm

**Comment by rohennes** [comment]
Looking at the above links, the only guidance that wouldn't be conflicting would be to disallow the incorrect forms:
Incorrect forms: x64, x86-64, or x86
Instead use either [64-bit x86 (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#bit-64-x86) or [x86_64 (noun)](https://redhat-documentation.github.io/supplementary-style-guide/#x86_64)
