### ISSUE TITLE
Linter results are updated dynamically in IDE without needed to close and re-open the topic

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/vale-at-red-hat#205]
**Describe the bug**
When using the vale-at-red-hat linter in Atom, if I fix a content quality issue that is flagged by the linter, the error/warning/info highlight persists and does not disappear inline until I save AND reopen the module.

**To Reproduce**

1. Create a module with content that you know is non-compliant, for example. use SSL instead of SSL/TLS to generate a red error.
2. Open the content in the Atom editor (with atomic-vale installed and configured)
3. Open the bad topic to view the error flag and hover over the bad phrase/word to see the advice offered.
4. Modify the bad word/phrase that has either an error, warning or info message. Change SSL to SSL/TLS.
RESULT: No change to the vale-at-red-hat linter output highlight. The red warning persists. But if you hover over the word, the guidance pop-up message no longer displays.
5. Save the topic.
RESULT: No change to the vale-at-red-hat linter output. and result of step 4.
6. Close the topic and re-open.
RESULT: The error, warning, or info message correctly disappears as expected.

**Expected behavior**
Linter issues are updated dynamically without the need to reopen a module, similar to how a spell checker works.
Rerun the linter on a Save event.

**Additional context**
Sometimes, I need to completely restart my Atom client. This is not reproducible.

**Comment by themr0c** [comment]
@michelle-purcell Atom being sunsetting, and everybody being told to switch to another IDE, do you agree on closing this issue without fixing it?

**Comment by michelle-purcell** [comment]
@themr0c I agree. Most folks have made the switch over to VS Code, IntelliJ or another IDE>

This issue is also intermittent and possibly specific to RHEL  CSB, It also depends on how many Atom windows are open too.
