### ISSUE TITLE
'Machine' incorrectly flagged with a style guide suggestion in instances of Java Virtual Machine (JVM)

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/vale-at-red-hat#209]
**Describe the bug**

The word 'Machine' is incorrectly flagged in instances of Java Virtual Machine (JVM):

![image](https://user-images.githubusercontent.com/92924207/165125568-7e4b42be-b3b9-4b3e-a191-cce790f7c3d4.png)

The suggestion is to 
`
vale: Verify your use of 'Machine' with the word usage guidelines. (RedHat.Usage)
`

**To Reproduce**

1. Add this word or expression: Java Virtual Machine 
2. Vale reports an illegitimate alert: error, warning, suggestion: 
* This word or expression triggers an illegitimate vale alert of type suggestion. 'Machine'

**Expected behavior**
Java Virtual Machine is a proper noun. It's an official product name. When your content includes 'Java Virtual Machine' this creates annoying suggestions, which can create unnecessary churn.

This relates to the following issue: https://github.com/redhat-documentation/vale-at-red-hat/issues/189
While issue 189 requests Red Hat product names are recognized, ideally commonly used third-party products and services should also be detected and excluded from style guidance.

**Comment by aireilly** [comment]
Fixed in https://github.com/redhat-documentation/vale-at-red-hat/pull/226
