### ISSUE TITLE
Headings.yml uses rule for capitalization based on IBM style guide rather than Red Hat's style guide

### ISSUE THREAD

**Issue by emteelb** [redhat-documentation/vale-at-red-hat#242]
```
match: $sentence
message: "Use sentence-style capitalization in '%s'."
scope: heading
source: "IBM - Capitalization in headings and titles, p.16"
```

However, Section 3.2 of Red Hat's Style Conventions for Writers and Editors, Edition 5.1, says to use "title case" for the Capitalization of headings:

>3.2. Heading Styles
> [...]
>Capitalization
>The standard for all Red Hat technical documentation is title case for all headings and titles. Table headings, procedure headings, and formal paragraph titles fall under this heading, and consequently, standard title case capitalization rules apply.

**Comment by themr0c** [comment]
See: https://redhat-documentation.github.io/vale-at-red-hat/docs/user-guide/redhat-style-for-vale/

I believe the current behavior is expected. The style in this repository is *not* based on Red Hat's Style Conventions for Writers and Editors, Edition 5.1, but on the Supplementary Style Guide https://redhat-documentation.github.io/supplementary-style-guide/ and IBM style guide.

**Comment by emteelb** [comment]
Thanks for the clarifying comment. This rule now makes sense to me.
