### ISSUE TITLE
Configure the Copy to clipboard widget to omit command prompt symbols?

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#266]
**Describe the bug**

The "Copy to clipboard widget" for code snippets copies the `$` command prompt at the beginning of the line. When users paste the command to their CLI, they must backspace and delete the prompt before pressing the Enter key. 

How might we fix this issue? 

**Reproduction steps:**
1. Visit https://redhat-documentation.github.io/vale-at-red-hat/docs/user-guide/installing-vale-cli/ . 
2. Scroll down to "3. Initialize the Vale package." 
3. Click the "Copy to clipboard widget" to the right of `$ vale sync`.
4. Paste the command into a text editor or terminal window.

![Screenshot from 2022-08-26 14-57-53](https://user-images.githubusercontent.com/350907/186973644-ed97e195-c476-48ff-bfe8-e313b0d2cb03.png)
![Screenshot from 2022-08-26 15-03-28](https://user-images.githubusercontent.com/350907/186974143-7a6e79af-2981-4bbc-ba8c-68787d1ecc55.png)

**Comment by aireilly** [comment]
CCS fix I think.

**Comment by rolfedh** [comment]
@themr0c Do you know anything about this widget or how it was enabled?

**Comment by rolfedh** [comment]
https://docs.antora.org/antora-ui-default/copy-to-clipboard/
