### ISSUE TITLE
When "config" is preceded by "Ignition" it should be allowed

### ISSUE THREAD

**Issue by mjpytlak** [redhat-documentation/vale-at-red-hat#272]
**Describe the bug**
"Ignition config" is a valid RHCOS term, but is being flagged.

Examples:

* The location to fetch the bootstrap Ignition config file from.
* Specify the infrastructure name that you extracted from the Ignition config file metadata.

**To Reproduce**

1. Add this word or expression: Ignition config
2. Vale reports an illegitimate alert: error

**Expected behavior**
"Ignition config" is not reported as an error.

**Additional context**
While the Red Hat Supplementary style guide does not list this combination as valid, I have confirmed with Kathryn Alexander that this is an approved item.

**Comment by aireilly** [comment]
could we use a `Vocab` with `accept.txt` and an `[Ii]gnition config` entry to fix this?

https://vale.sh/docs/topics/vocab/

**Comment by rolfedh** [comment]
@aireilly resolved, or more to do for this issue?

**Comment by aireilly** [comment]
Not resolved - we don't want to use vocabs in our rules. I think we need to throw out the config map rule and create simple spelling exceptions for the various config terms we want to allow.

**Comment by aireilly** [comment]
Fixed in https://github.com/redhat-documentation/vale-at-red-hat/pull/319
