### ISSUE TITLE
Too many false positives for `Do not use 'config', unless it is followed by 'map'.`

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#305]
This [Vale error log](https://docs.google.com/spreadsheets/d/1nYu77sKaR7IZDrigUYANsbuMA4Mj3xZPSIClTe2rWMY/edit?usp=sharing) shows `Do not use 'config', unless it is followed by 'map'.` as one of the top ten errors. 

Remove this rule and replace it with one that very specifically targets the incorrect forms, "configmap" and "configuration map," which are listed here: https://redhat-documentation.github.io/supplementary-style-guide/#config-map

Then, evaluate the following cases and see if we might add helpful suggestions or warnings for "config"

[config-not-map.txt](https://github.com/redhat-documentation/vale-at-red-hat/files/9559753/config-not-map.txt)

**Comment by rolfedh** [comment]
.vale/styles/RedHat/ConfigMap.yml

**Comment by aireilly** [comment]
I think we should remove config map altogether: https://github.com/redhat-documentation/vale-at-red-hat/pull/319

**Comment by rolfedh** [comment]
@aireilly created and merged: https://github.com/redhat-documentation/vale-at-red-hat/pull/319
Let's consider this issue closed for now and open a new one if there are follow up issues.
