### ISSUE TITLE
@themr0c - Can you confirm whether the WARNING is still needed? It was still in the content that was recently updated. Thanks.

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#309]
About the following warning in `modules/user-guide/pages/using-vale-github-action.adoc`
```
WARNING: Because of GitHub token permissions, the Vale GitHub Action cannot post annotations to pull requests from a forked repository.
```

@themr0c - Can you confirm whether the WARNING is still needed? It was still in the content that was recently updated. Thanks.

_Originally posted by @michelle-purcell in https://github.com/redhat-documentation/vale-at-red-hat/pull/303#discussion_r970006058_

**Comment by themr0c** [comment]
Not relevant any more

**Comment by themr0c** [comment]
Implemented, closing
