### ISSUE TITLE
New members

### ISSUE THREAD

**Issue by themr0c** [redhat-documentation/vale-at-red-hat#318]
Please add active contributors to the [vale-at-red-hat group](https://github.com/orgs/redhat-documentation/teams/vale-at-red-hat/members):
 
* @deerskindoll 
* @michelle-purcell 
* @jhradilek 
* @osslate
* @apupier
* @abhatt-rh
* @mjahoda 
* kquinn1204

**Comment by kquinn1204** [comment]
kquinn1204

**Comment by rohennes** [comment]
rohennes

**Comment by pmkovar** [comment]
Invites sent to current non-members.
