### ISSUE TITLE
Vale rule about `ConfigMap` is an error

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/vale-at-red-hat#326]
**Describe the bug**

The word `ConfigMap` triggers an illegitimate Vale error:
![image](https://user-images.githubusercontent.com/78564304/193532218-01381731-266f-46fb-83ee-ae7eb7644cec.png)
The supplementary style guide does not tell us to use `config map` rather than `ConfigMap`, so the error and its message are incorrect.

I've looked up the [supplementary style guide](https://redhat-documentation.github.io/supplementary-style-guide/#_c), and
a) `ConfigMap` is stated in the description for `config map`: `The API object for a config map is ConfigMap.`.
b) `ConfigMap` is not listed among the incorrect forms for `config map`: `Incorrect forms: configmap, configuration map`

![image](https://user-images.githubusercontent.com/78564304/193530938-91c107c7-d4ff-4081-a3c4-b12e1212fb46.png)

**To Reproduce**
1. Add `ConfigMap` in a text.
2. Vale reports an illegitimate alert: error.

**Expected behavior**
1. Make the trigger word in the rule to be case-sensitive: only the lower-case `configmap`, and not `ConfigMap`.
2. Retain the error level of the alert.
3. The error message has to offer the Vale user both alternatives, something like this:
```
Use either 'config map' or '`ConfigMap`' as appropriate to your text.
```
4. Add a new Vale rule for `ConfigMap`: only for the Pascal case without back ticks, and not `configmap`.
5. Make the new rule for `ConfigMap` in the previous point an error.
6. The error message has to ask the Vale user to verify that they really meant the Pascal-case `ConfigMap`, something like this:
```
If 'ConfigMap' refers to an API object, enclose it in back ticks: '`ConfigMap`'.
```
By the way, what happens to occurrences of 'ConfigMap' without back ticks inside 'yaml' code blocks? Will those be treated as errors by Vale?

**Additional context**
Please prioritize this issue because it's blocking a PR with multiple instances of this error.

**Comment by aireilly** [comment]
I think this issue can be marked as invalid/won't fix - `ConfigMap` as an API reference should be marked up with backticks, which would remove the error. Open to correction on this.

**Comment by max-cx** [comment]
> ConfigMap as an API reference should be marked up with backticks

The current error message instructs the Vale user to write it as 'config map', contrary to your advice.
If this is a won't fix, then I'll have to follow the Vale instruction and fix all errors as 'config map', not '`ConfigMap`'.

**Comment by aireilly** [comment]
> By the way, what happens to ConfigMap occurrences without back ticks within yaml code blocks?

Vale ignores all text that is in codeblocks or markup that is not in body text or titles.

I do take your point that the error message is confusing, but I don't see a fix for this other than to mark up the ConfigMap element correctly with backticks.

**Comment by aireilly** [comment]
> If this is a won't fix, then I'll have to follow the Vale instruction and fix all errors as 'config map', not 'ConfigMap'.

Well - if you are referring to an API object, you could mark up the ``ConfigMap`` elements with backticks as prescribed by the Style guide.

**Comment by max-cx** [comment]
> I don't see a fix for this other than to mark up the ConfigMap element correctly with backticks.

Question 1: Aren't Vale rules case-sensitive?
Question 2: Will the solution I suggested in the description not work?

**Comment by max-cx** [comment]
>>  If this is a won't fix, then I'll have to follow the Vale instruction and fix all errors as 'config map', not 'ConfigMap'.

> Well - if you are referring to an API object, you could mark up the ConfigMap elements with backticks as prescribed by the Style guide.

Yes, and my suggestion is to make this the error message. Vale relies on error messages to instruct users. No user should be opening an issue and having this discussion here.

**Comment by themr0c** [comment]
Is it an OpenShift style rule, or a Supplementary Style Guide rule?

If that's an OpenShift rule, it doesn't belong to the RedHat style.

The introduced change is annoying, as it is breaking the build in many places in Che docs, where we consider ConfigMap as legit.

**Comment by aireilly** [comment]
https://redhat-documentation.github.io/asciidoc-markup-conventions/ I think ConfigMap would be covered under System item, daemon, or service and requiring backticks.

Also playing with changes in https://github.com/redhat-documentation/vale-at-red-hat/pull/327 to add a camel case/pascal case rule

**Comment by aireilly** [comment]
> Can't it all be just case-sensitive rules that, if the upper case is detected, require back ticks to be added?

 But wouldn't that catch the first word in every sentence? That would be incorrect. I think single word API references would need specific entries in a rule. It's not ideal.

**Comment by max-cx** [comment]
> But wouldn't that catch the first word in every sentence? 

You mean `Pod`, `Nod`, and `Deployment` that occur as the first word in a sentence? I don't know what the probability of that happening is.

> I think single word API references would need specific entries in a rule. It's not ideal.

It's not ideal, but if you want Vale to enforce this rule, then Vale should enforce the rule for all declared terms that the rule specifies. The other alternative is not make it a Vale rule.
