### ISSUE TITLE
Incorrect product name flagged as an error

### ISSUE THREAD

**Issue by elianerpereira** [redhat-documentation/vale-at-red-hat#338]
Vale flags the product name "Red Hat Satellite"as incorrect, with the following message: " error (RedHat.CaseSensitiveTerms ) Use 'Red Hat Network Satellite Server' rather than 'Red Hat Satellite'.              

The Official Red Hat product and solution names list uses "Red Hat Satellite".
This should be corrected. Thank you.

**Comment by rolfedh** [comment]
```
Red Hat Satellite is a system management solution that enables you to deploy, configure, and maintain your systems across physical, virtual, and cloud environments. Satellite provides provisioning, remote management and monitoring of multiple Red Hat Enterprise Linux deployments with a single, centralized tool.

Red Hat Satellite Server synchronizes the content from Red Hat Customer Portal and other sources, and provides functionality including fine-grained life cycle management, user and group role-based access control, integrated subscription management, as well as advanced GUI, CLI, or API access.

Red Hat Satellite Capsule Server mirrors content from Red Hat Satellite Server to facilitate content federation across various geographical locations. Host systems can pull content and configuration from the Capsule Server in their location and not from the central Satellite Server. The Capsule Server also provides localized services such as Puppet Master, DHCP, DNS, or TFTP. Capsule Servers assist you in scaling Red Hat Satellite as the number of managed systems increases in your environment.
```
See https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html-single/release_notes/index#pref-Red_Hat_Satellite-Release_Notes-Introduction

**Comment by rolfedh** [comment]
https://www.redhat.com/en/technologies/management/satellite

**Comment by rolfedh** [comment]
"Red Hat Network Satellite Server"
https://www.google.com/search?q=%22Red+Hat+Network+Satellite+Server%22&oq=%22Red+Hat+Network+Satellite+Server%22&aqs=chrome.0.69i59.1230j0j1&sourceid=chrome&ie=UTF-8

**Comment by msuchane** [comment]
Hi @rolfedh, I don't have that much to add because I've never documented Satellite. The changes in https://github.com/redhat-documentation/vale-at-red-hat/pull/343 look reasonable, though.
