### ISSUE TITLE
Doc topic: How to validate a rule change locally - for example, against a repo

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#349]
Doc topic: How to validate a rule change locally - for example, against a repo

I'd like to explore and document a procedure for validating a rule change by running it against a large doc repo.

**Comment by rohennes** [comment]
You can run Vale recursively against a folder like this:
`vale modules/ --glob='*.adoc' --output=JSON --no-exit`

They are optional arguments of course, see more info on the CLI arguments here: https://vale.sh/manual/

The documentation can be updated probably somewhere here: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/using-vale-cli/

**Comment by rolfedh** [comment]
As the creator of this issue and after reviewing our current priorities, I notice this issue has become stale without recent activity. I'm closing it for now. If it's still relevant or needs attention, please feel free to reopen it with new information. Thanks for your understanding.
