### ISSUE TITLE
Add a clustertask set of rules

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#355]
The current style rules don't flag misuse of "clustertask":
https://coreos.slack.com/archives/G01Q6LPP04S/p1665498070744289?thread_ts=1665497283.780329&cid=G01Q6LPP04S

* `clustertask` command
* `ClusterTask` object
* "cluster task" in ordinary language

**Comment by rohennes** [comment]
Hey @rolfedh - I don't have access to that Slack conversation. Any more light on that? Are there any 'official' guidelines on this? I couldn't see any in the SSG etc

**Comment by rolfedh** [comment]
Thanks for asking, @rohennes.
This issue derives from [these openshift-docs contributor guidelines for object references](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#api-object-object-references). 
I don't see similar guidelines in the ISG or SSG, so I'm not sure this needs a rule after all.
The Style Council should probably discuss it before continuing.

**Comment by rolfedh** [comment]
To summarize the issue:
When we're not referring to a specific object or command (between backticks), we use ordinary words.

For example, the following usages are all good:
-  "A`clustertask` command"
- "A `ClusterTask` object:
- "a cluster task"

But we should avoid writing "a clustertask".

This is a common issue with other words that some contributors tend to glom together. 

Related: "config map" vs. "ConfigMap" vs. "configuration map"

**Comment by rolfedh** [comment]
I've cross-posted this issue to the CCS Style Council channel in gchat.

**Comment by rolfedh** [comment]
@rohennes Here's the thread from CCS Style Council channel in gchat:

Andrea Hoffer, Yesterday 1:41 PM
@Rolfe Dlugy-Hegwer we had a similar question come up in this issue: https://github.com/redhat-documentation/supplementary-style-guide/issues/169. though it was closed because the IBM style guide had the required guidance

i think this section should answer your question enough: https://www.ibm.com/docs/en/ibm-style?topic=elements-programming

it recommends putting the type after keyword, instead of using keywords alone

Breda McColgan, Yesterday 1:42 PM
I think the advice is provided in the relevant topics in IBM Style, as shown in the following examples:

"Generally, when you specify the name of a command, parameter, or option in text, specify the word command, parameter, or option after the name. "
         https://www.ibm.com/docs/en/ibm-style?topic=elements-commands

"Generally, do not use a file name, file name extension, file type, or directory name as a noun. Instead, use the file name, file name extension, file type, or directory name as an adjective in one of the following ways:
         Follow the file name, file name extension, or file type with the word file, and follow the directory name with the word directory."
         https://www.ibm.com/docs/en/ibm-style?topic=elements-files-directories

"Generally, specify the keyword type after the keyword. Keywords are not translated; so without the keyword type, users might be confused about what the keyword represents."
         https://www.ibm.com/docs/en/ibm-style?topic=elements-programming

The advice might not be explicitly repeated for each type of object, but the same pattern is used. For example, see the Keyboard keys topic:
https://www.ibm.com/docs/en/ibm-style?topic=elements-keyboard-keys

Breda McColgan, Yesterday 1:45 PM
Ha, snap Andrea! 🤝

Jamie Prevatt, Yesterday 1:47 PM
I almost pressed enter at the same time that @Breda McColgan added the info about the commands section. Now we know approximately how long it takes to get to an IBM Style reference.

**Comment by rolfedh** [comment]
Thanks for citing the https://github.com/redhat-documentation/vale-at-red-hat/pull/334 rule, @rohennes.
