### ISSUE TITLE
Remove "Due to"?

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#379]
**Describe the bug**

Running vale with the Red Hat style against the following text [1] generates the following suggestion [2].

[1]
```
Due to resource and process-efficiency limitations, {ProductLongName} {ProductVersion} does not provide a Java 11-based Mandrel 22.3 base image for building native executables.
```

[2]
```
95:1     suggestion  Verify your use of 'Due         RedHat.Usage               
                      to' with the word usage                                    
                      guidelines. 95:1     suggestion  Verify your use of 'Due         RedHat.Usage               
                      to' with the word usage                                    
                      guidelines. 
```

However, when I searched the _IBM Style Guide_ and _Red Hat supplementary style guide for product documentation_, I didn't see any word usage guideline that mentions "due to". Perhaps this is a legacy item from a much earlier edition of these references?

If there is no supporting guideline, we should remove this suggestion.

**Comment by rohennes** [comment]
Fixed in #419
