### ISSUE TITLE
Add 'etcd' to the rule list; flag 'Etcd' as an error

### ISSUE THREAD

**Issue by tmalove** [redhat-documentation/vale-at-red-hat#389]
**Describe the bug**
The term 'etcd' should always be lowercase with no uppercase characters allowed (i.e. Etcd, ETCD, etc.). Add 'etcd' to the allowed terms and flag any uppercase derivatives.

Examples: etcd

* This word triggers an illegitimate vale suggestion.

1. Add this word or expression: etcd
2. Vale reports an illegitimate alert: suggestion.

**Expected behavior**
Allow 'etcd' as a valid term, even if it starts a sentence. Disallow any other forms of the word.

**Comment by abhatt-rh** [comment]
> Allow 'etcd' as a valid term, **even if it starts a sentence**. Disallow any other forms of the word.

Hi @tmalove, 
Thank you for submitting this issue.  

I noticed that the highlighted bit from the _expected behavior_ seems to violate the [ISG recommendation ](https://www.ibm.com/docs/en/ibm-style?topic=grammar-capitalization#general-text) that states:

> Do not start a sentence with a lowercase term; rewrite the sentence.
> 
> Incorrect example onmouseover events can add visual interest.
> Correct example You can add visual interest by using onmouseover events.

May I request you to kindly update the _expected behavior_ to comply with the ISG guideline?
