### ISSUE TITLE
The main branch is currently unprotected

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#399]
The main branch is currently unprotected. This could lead to accidental pushes to main. Ref @rolfedh : https://coreos.slack.com/archives/C0218RXJK5E/p1671200325566779?thread_ts=1671193107.605219&cid=C0218RXJK5E

**Comment by rolfedh** [comment]
About protected branches
https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by themr0c** [comment]
* Require pull request
* Require 1 approval
* Require status check: 'Build and publish to publication branch'
* Require conversation resolution
