### ISSUE TITLE
Should we migrate unfinished stories out of "Project 2" and close it

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#401]
**Is your feature request related to a problem? Describe.**

We created the ["Docs for VaRH" project board](https://github.com/redhat-documentation/vale-at-red-hat/projects/2) a while ago and it isn't used much anymore.
Much of the work the stories in this project board describe has been completed or no longer makes sense. However, there might be some follow-up tasks or items that are still in progress.

**Describe the solution you'd propose**

Let's discuss cleaning up the repo. 
We can identify any tasks that still need to be done and create standard issues them.
Then we can mark the stories in this project board as _Done_ or simply delete project 2.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tmalove** [comment]
I have part of a user story to update the user guide with installation information that I can track as an issue. Based on any open items after that, we can possibly close this project.

**Comment by rolfedh** [comment]
I closed project #1. 
I migrated project #2 to the new project experience.
