### ISSUE TITLE
The 'due to' is no longer in the IBM Style Guide

### ISSUE THREAD

**Issue by ragevou** [redhat-documentation/vale-at-red-hat#417]
In the previous versions of IBM Style Guide, the usage of the _'due to'_ was unwanted. The new version of it no longer has it mentioned.

*note | Verify your use of 'due to' with the word usage guidelines. (RedHat.Usage)*

I suggest to delete this message from vale.

**Comment by rolfedh** [comment]
Thank you, @ragevou. Fixed.
