### ISSUE TITLE
Added glossary entry for Basic HTTP authentication

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#424]
New guideline [added in to SSG in January](https://github.com/redhat-documentation/supplementary-style-guide/blob/main/HISTORY.md#2023-january). Evaluate the following for opportunities to improve the VaRH style rules:
Added glossary entry for [Basic HTTP authentication](https://redhat-documentation.github.io/supplementary-style-guide/#basic-http-authentication)

**Comment by rohennes** [comment]
This was addressed here: 
https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/CaseSensitiveTerms.yml#L64
