### ISSUE TITLE
'desynchronize' and 'desynchronized' are correct

### ISSUE THREAD

**Issue by themr0c** [redhat-documentation/vale-at-red-hat#439]
The `RedHat.Spelling` rule reports an error on 'desynchronize' and 'desynchronized'.

However, according to the Merriam-Webster dictionary, these words are correct.

See: https://www.merriam-webster.com/medical/desynchronize

**Comment by rolfedh** [comment]
Additionally, neither the SSG nor the IBM Style has entries for these terms.
