### ISSUE TITLE
Missing redirections in the docs website

### ISSUE THREAD

**Issue by themr0c** [redhat-documentation/vale-at-red-hat#453]
The docs website is missing redirects for pages that were published and have backlinks.

For example, links in https://vale.sh/hub/redhat/ lead to 404 errors.

Possible mitigation:

1. Update the links in https://vale.sh/hub/redhat/
2. Add proper redirects (page-aliases)

**Comment by rohennes** [comment]
Not seeing any 404 errors in the links on https://vale.sh/hub/redhat/ 

Can this be closed?
