### ISSUE TITLE
vale reports an error for referring to x86_64 rather than AMD64, even when describing an x86_64 command

### ISSUE THREAD

**Issue by mnsteven** [redhat-documentation/vale-at-red-hat#462]
The command to enable a repository for the various cluster and resilient storage repositories includes x86_64 (this one for rhel 8 resilient storage):

subscription-manager repos --enable=rhel-8-for-x86_64-resilientstorage-rpms

When I describe that command, I note that this is the example to use for an x86_64 system.  Vale tells me that this is an error.  But to say to use this command for an AMD64 system seems confusing there.  I checked with the technical PM on the project who said:

"that error message is not valid in this case.

Maybe if you were to refer to the x86_64 architecture outside of actual commands they want you to refer to it as AMD64, but not in the --enable command."

So you could say that when I'm introducing the command I am referring the to architecture outside of the actual command, but it still seems confusing in this case and I'm not sure it would be helpful to the user to call the architecture one thing in the text and another thing in the command/repository name.

**Comment by aireilly** [comment]
```asciidoc
[source,terminal]
----
$ subscription-manager repos --enable=rhel-8-for-x86_64-resilientstorage-rpms
----
```

When we describe commands in our docs, the AsciiDoc style requires commands to be marked up as codeblocks with appropriate huighlighting applied. See: https://redhat-documentation.github.io/asciidoc-markup-conventions/

**Comment by aireilly** [comment]
Having said that, there is a long standing issue on the [Supplementary Style Guide GH repo](https://github.com/redhat-documentation/supplementary-style-guide/issues/171) which I am following. I think we will need to update our rules based on the outcome of this.

**Comment by mnsteven** [comment]
The problem is not in the codeblock, but in the description that precedes the codeblock:

"Enable the repository for Resilient Storage that corresponds to your system architecture. For example, to enable the Resilient Storage repository for an x86_64 system, enter the following subscription-manager command: "

As noted in my description:

"So you could say that when I'm introducing the command I am referring the to architecture outside of the actual command, but it still seems confusing in this case and I'm not sure it would be helpful to the user to call the architecture one thing in the text and another thing in the command/repository name."

**Comment by aireilly** [comment]
Ah OK, my bad. I understand. I think we can adjust this and not report an error. I'll submit a PR.

**Comment by aireilly** [comment]
CLosing this, demoted the x84_64 rule to a suggesiton. Hope this works.

**Comment by mnsteven** [comment]
Thanks.  It's psychological since it doesn't prevent a document from building or merging, but the word "error" is something I am not comfortable ignoring.

**Comment by aireilly** [comment]
It can be material too - some teams have configured CI builds to fail if the content has a Vale error. So we really don't want to flag Vale errors unless they really _are_ errors. 

Please raise any other issues as you find them. It helps make the Style better :)
