### ISSUE TITLE
Making "information on" an error rather than a suggestion creates false errors.

### ISSUE THREAD

**Issue by mnsteven** [redhat-documentation/vale-at-red-hat#472]
I don't actually agree that using the phrase "information about" rather than "information on" should be an error, but I'm willing to go along with that.  Except I am getting an actual error for this sentence:

"This ensures that the NFS servers are storing their stateful information
on a device that will become available to another node if this resource group
needs to relocate. "

This should not yield an error.

**Comment by aireilly** [comment]
Agree this should be demoted to suggestion.

**Comment by aireilly** [comment]
related: https://github.com/redhat-documentation/vale-at-red-hat/issues/476

**Comment by deerskindoll** [comment]
https://github.com/redhat-documentation/vale-at-red-hat/pull/487
