### ISSUE TITLE
Do not run RedHat.CaseSensitiveTerms on IDs

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/vale-at-red-hat#524]
**Describe the bug**
[newdoc](https://github.com/redhat-documentation/newdoc) creates IDs for assemblies and modules in lower case. Therefore, running RedHat.CaseSensitiveTerms on IDs should be disabled.

Examples:
```
[id="proc_connecting-to-a-wifi-network-by-using-the-gnome-settings-application_{context}"]
```
causes vale to report
```
 3:53    error       Use 'GNOME' rather than         RedHat.CaseSensitiveTerms 
                     'gnome'. 
```

**To Reproduce**
1. Create an AsciiDoc file with the following content:
```
:_content-type: PROCEDURE

[id="proc_connecting-to-a-wifi-network-by-using-the-gnome-settings-application_{context}"]
= Connecting to a wifi network by using the GNOME settings application

Lorem ipsum dolor sit amet,...
```
2. Run vale. It reports an error for line 3: `Use 'GNOME' rather than 'gnome'.`

**Expected behavior**
No case sensitive checks on IDs.

**Comment by mmuehlfeldRH** [comment]
Is this expected: I received an email from GitHub after reporting this issue that says:
```
Pull request opened: All jobs have failed
View workflow run: https://github.com/redhat-documentation/vale-at-red-hat/actions/runs/4913712102
Pull request opened / pull-request-opened
Failed in 2 seconds
```
I didn't open a pull request. I only reported this issue.

**Comment by rohennes** [comment]
Closing this unless any objections @michelle-purcell ? I don't think the rules should run on syntax unless the scope is set to raw.

**Comment by michelle-purcell** [comment]
@rohennes - I agree :+1:  Thanks.
