### ISSUE TITLE
Add AsciiDoc and OpenShiftAsciiDoc as Vale packages

### ISSUE THREAD

**Issue by rohennes** [redhat-documentation/vale-at-red-hat#531]
Currently in the packages field we're pointing to the zip files in the VRH releases. We can ask JD Kato to include these as Vale packages, similar to the RedHat package.

**Comment by aireilly** [comment]
https://github.com/errata-ai/packages/pull/15

**Comment by aireilly** [comment]
Need to change docs to reflect this update. Leaving this issue open until docs get updated.

**Comment by aireilly** [comment]
This is fixed.

**Comment by rohennes** [comment]
Duplicate of https://github.com/redhat-documentation/vale-at-red-hat/issues/618, closing.
