### ISSUE TITLE
[chore] Add "Ansible Playbook" to Vale at Red Hat rules

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#638]
[Ansible Playbook](https://redhat-documentation.github.io/supplementary-style-guide/#ansible-playbook) has a listing for incorrect capitalization in the Red Hat supplementary style guide.

1. Add the term in the form `bad: good` to the `.vale/fixtures/RedHat/CaseSensitiveTerms.yml` rule.
2. Update the test fixtures: 
    * `.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc`
    * `.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc`
    
Use `Ansible playbook: Ansible Playbook` in the rule.

PR must be reviewed and all tests must pass before merging.

**Comment by michellemacrh** [comment]
I can take on this issue. I worked on the PR for Ansible Playbook and Rulebook recently :)

**Comment by michellemacrh** [comment]
The PR for this issue has been approved and merged. I think this issue is OK to close if there are no more issues?
