### ISSUE TITLE
[chore] Add "softirq" to Vale at Red Hat rules

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#640]
[softirq](https://redhat-documentation.github.io/supplementary-style-guide/#softirq) has a listing for incorrect capitalization in the Red Hat supplementary style guide.

1. Add the term in the form `bad: good` to the `.vale/fixtures/RedHat/CaseSensitiveTerms.yml` rule.
2. Update the test fixtures: 
    * `.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc`
    * `.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc`
    
Use `SoftIRQ: softirq` in the rule.

PR must be reviewed and all tests must pass before merging.

**Comment by dfitzmau** [comment]
Hi @aireilly . I can take on this Issue. Do you need to assign me to it? I'm unable to access that option.

**Comment by aireilly** [comment]
Thanks @dfitzmau !

**Comment by dfitzmau** [comment]
Thanks for merging my PR, @aireilly. I'm unable to close this Issue, but can you close it on my behalf?
