### ISSUE TITLE
[chore] Add "Application Stream" and  "AppStream repository" to Vale at Red Hat rules

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#642]
[Application Stream](https://redhat-documentation.github.io/supplementary-style-guide/#application-stream) and [AppStream repository](https://redhat-documentation.github.io/supplementary-style-guide/#appstream-repository) have listings for incorrect usages in the Red Hat supplementary style guide.

1. Add the terms in the form `bad: good` to the `.vale/fixtures/RedHat/CaseSensitiveTerms.yml` rule.
2. Update the test fixtures: 
    * `.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc`
    * `.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc`
    
Use `application stream|Application stream: Application Stream` and `Appstream|appstream: AppStream repository` in the rule.

PR must be reviewed and all tests must pass before merging.

**Comment by Utkarsh212** [comment]
Please assign this issue to me.
