### ISSUE TITLE
[chore] Add "quick start" to Vale at Red Hat rules

### ISSUE THREAD

**Issue by aireilly** [redhat-documentation/vale-at-red-hat#643]
[Quick start](https://redhat-documentation.github.io/supplementary-style-guide/#quick-start) has a listing in the Red Hat supplementary style guide.

1. Add the term in the form `bad: good` to the `.vale/fixtures/RedHat/TermsErrors.yml` rule.
2. Update the test fixtures: 
    * `.vale/fixtures/RedHat/TermsErrors/testinvalid.adoc`
    * `.vale/fixtures/RedHat/TermsErrors/testvalid.adoc`
    
Use `quickstart: quick start` in the rule.

PR must be reviewed and all tests must pass before merging.

**Comment by Utkarsh212** [comment]
Please assign this issue to me.
