### ISSUE TITLE
[chore] "role-based access control" to the Vale at Red Hat case-sensitive rules

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/vale-at-red-hat#646]
The security term "[role-based access control (RBAC) ](https://en.wikipedia.org/wiki/Role-based_access_control)" is often incorrectly capitalized, especially in raw developer docs that Red Hat writers edit and polish.

Add the term in the form bad: good to the .vale/fixtures/RedHat/CaseSensitiveTerms.yml rule.
Update the test fixtures:
.vale/fixtures/RedHat/CaseSensitiveTerms/testinvalid.adoc
.vale/fixtures/RedHat/CaseSensitiveTerms/testvalid.adoc

Use ...
Role Based Access Control | Role-Based Access Control| role based access control : [rR]ole-based access control

PR must be reviewed and all tests must pass before merging.

**Comment by Utkarsh212** [comment]
Please assign this issue to me.
