### ISSUE TITLE
The word "wifi" is reported as warning

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/vale-at-red-hat#666]
**Describe the bug**
Vale doesn't seem to know the word "wifi".

Examples:
```
 5:17    warning     Use correct American English    RedHat.Spelling         
                     spelling. Did you really mean                           
                     'wifi'? 
```

**To Reproduce**

1. Add the word "wifi" to a text file.
2. Run vale against the file.

**Expected behavior**
"wifi" should not show a warning

**Additional context**
IBM Style guide:
```
wifi adjective, noun
Write as shown (one word, unhyphenated, with lowercase w and f) for generic references to a wireless
connection. For specific and official references to the Wi-Fi Alliance and the services that it certifies, use Wi-
Fi. Wi-Fi is a registered trademark of the Wi-Fi Alliance.
```

By the way, the spelling "Wi-Fi" doesn't show a warning or error in Vale, which is Ok (in the case mentioned in the IBM Style Guide).

**Comment by alexpdp7** [comment]
<joking>Can we discourage the use of the word? I reaaaally don't like it</joking>

**Comment by mmuehlfeldRH** [comment]
@alexpdp7 I think the differentiation makes sense. For example, "Wi-Fi Protected Access 3 (WPA3)" is a standard from the Wi-Fi alliance, while a sentence like "use this tool to connect to a wifi network" refers to wifi networks in general and not to anything that associated with the trademark holder.

[Open RAN](https://redhat-documentation.github.io/supplementary-style-guide/#open-ran), [OpenRAN](https://redhat-documentation.github.io/supplementary-style-guide/#openran), and [O-RAN](https://redhat-documentation.github.io/supplementary-style-guide/#o-ran) also have their own use cases. Wi-Fi vs. wifi is similar.

**Comment by alexpdp7** [comment]
Oh, sorry- I thought I was in a very different repository (I collaborate in a different Vale rules repo). In general, yeah, `wifi` should not be disallowed. In the other repo context, we would be able to disallow `wifi`, I think.

Apologies for the noise.
