### ISSUE TITLE
Use double quotes, not single, in IDs

### ISSUE THREAD

**Issue by rohennes** [redhat-documentation/vale-at-red-hat#672]
I don't think it causes a build issue, but this is non-standard:

[id='support-overview-remote-health-monitoring']

Should use double quotes:

[id="support-overview-remote-health-monitoring"]

**Comment by michellemacrh** [comment]
Interesting to note, thanks for the feedback 👍 

"As a project style rule" - Does that refer to a .vale.ini file outside of the vale-at-red-hat repo?

**Comment by rohennes** [comment]
I think this came from a peer review comment in the OpenShift docs. As it's not bad AsciiDoc, perhaps it's better not to flag as an error in the AsciiDoc rule set. 

As Aidan alluded to, if this went against style guidelines for a particular project, for example RHEL or OpenShift or whoever, you could create a rule for it and include it in the project's rule set. And yes, the .vale.ini file is how you configure Vale in a repo, for example, what rules you want turned on or off in a rule set, or what rule sets (or packages) you want to use etc.

**Comment by michellemacrh** [comment]
Thanks for your comments @rohennes. I'm still getting to grips with using Vale so this info is helpful :) 

In terms of helping to resolve this issue, is it a matter of moving this rule into OpenShiftAsciiDoc, or does this need to be addressed within the OpenShift docs themselves?

**Comment by rohennes** [comment]
Typically these types of rules might hang off some project-specific guidance. We don't have a rule about this in the OpenShift style guidelines though. So it's probably solving an issue that doesn't really exist. I got a review comment about it but perhaps that was just one reviewer's preference rather then a hard rule.

Sorry if this issue was a wild goose chase but probably need to drop it unless you can find some project that really disallows this. The updates in your PR looked good otherwise!

**Comment by rohennes** [comment]
You could try asking the mod docs people if they want to mandate for double-quotes by opening an issue? You could add it to the Red Hat rule set then. It's a bit of a long shot though. https://github.com/redhat-documentation/modular-docs/issues

**Comment by michellemacrh** [comment]
Thanks @rohennes, I'll take a look :)

**Comment by aireilly** [comment]
We support single and double quotes in the rules FYI: https://github.com/redhat-documentation/vale-at-red-hat/pull/613

I don't think we need to change this tbh
