### ISSUE TITLE
[BUG] .vale folder missing after installation on some machines

### ISSUE THREAD

**Issue by oafischer** [redhat-documentation/vale-at-red-hat#722]
**Describe the bug**
When installing Vale by following the [official instructions](https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/installing-vale-cli/), the `.vale` folder might not download. This causes an error and does not allow you to complete the installation. This only affects some machines. Even when following the exact same steps, some machine don't encounter issues, while others don't.

**To Reproduce**

1. Follow the instructions up to and including step 3: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/installing-vale-cli/
2. When running the command in step 4, an error message that resembles the following appears sometimes: `cannot find /home/.vale`

**Expected behavior**

The `.vale` folder downloads correctly every time and after running `vale sync`, no error message appears.

**Additional context**

The team was using macOS. The error is intermittent and cannot be reliably reproduced. Everyone in my team followed the same steps in a meeting with screen share. 2 team members had no issues, but 2 team members encountered the error.

We were able to resolve the error and continue with the installation by copying the missing `.vale` folder from the team members that had a successful install/download to the team members who encountered the error. After placing the missing folder manually, they could run step 4 with no issues.

All machines involved had homebrew installed, but the exact packages on each machine might differ. For example, some of them might have had `wget` while others didn't.

Unfortunately, I did not save the exact error message.

**Comment by aireilly** [comment]
Thanks for reasing this! I think this is probably related to folder permissions. For example, this is OK:

```cmd
$ ll -d ~/openshift-docs
drwxr-xr-x. aireilly aireilly 5.0 KB Wed May 22 12:28:46 2024  /home/aireilly/openshift-docs
```

If you see this error again, please reopen this bug with details of the folder.
