### ISSUE TITLE
OpenShiftAsciiDoc rule: no xref in modules is not working as expected

### ISSUE THREAD

**Issue by rohennes** [redhat-documentation/vale-at-red-hat#754]
In the OpenShiftAsciidoc rules, the xrefs in modules rule isn't firing:

![image](https://github.com/redhat-documentation/vale-at-red-hat/assets/104497497/680f9b58-500f-42af-8801-2839b17ee348)

![image](https://github.com/redhat-documentation/vale-at-red-hat/assets/104497497/8c359b15-70bf-4ad7-a0ac-ff04bdf3f79c)

**Comment by gaurav-nelson** [comment]
@rohennes Don't we allow snippets into modules? The rule only checks for the existence of `xref`. We can update the rule if snippets are not allowed, as technically, they are links. I'll check with the OCP docs team.

**Comment by gaurav-nelson** [comment]
Snippets are allowed in modules, but they cannot contain xrefs. One solution is to create a rule to check for xrefs in snippets and flag them.

**Comment by rohennes** [comment]
Include statements that point to snippets should not be flagged in modules in the OCP repo:

This should be ok:
`include::snippets/snip-private-clusters-public-ingress.adoc[]`

This is the rule. The regex should exclude statements that point at snippets: https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/OpenShiftAsciiDoc/NoNestingInModules.yml

[This rule](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/OpenShiftAsciiDoc/NoXrefInModules.yml) flags xrefs in modules only. It is only turned on in our modules folder. In the higher level assembly folder, it's disabled. 

Hope that sheds some light?

**Comment by rohennes** [comment]
Xrefs are now being flagged as expected, this is a related fix. A Vocab rule was overriding the xref rule. Removing a Vocab entry allowed xrefs to be flagged: https://github.com/openshift/openshift-docs/pull/74513

**Comment by gaurav-nelson** [comment]
Feel free to close this. @rohennes Thanks.
