### ISSUE TITLE
Add error or warning for GitHub links

### ISSUE THREAD

**Issue by apinnick** [redhat-documentation/vale-at-red-hat#828]
[OpenShift](https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#links-to-external-websites) does not allow links to GitHub repositories unless they are in auto-generated API references. Other projects require project management approval. The [RHSSG](https://redhat-documentation.github.io/supplementary-style-guide/#external-links) also does not allow links to GitHub. I think it would be a good idea to add a rule to detect GitHub links.

**Comment by aireilly** [comment]
Great idea! Do you want to put this in? Something like this would work: 

---
extends: substitution
ignorecase: false
level: error
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/github/
message: "%s"
scope:raw
swap:
  # Start each error message with "Do not use ..."
  # Error messages must be single quoted.
  'https://github.com/': 'Do not GitHub links in source.'

**Comment by apinnick** [comment]
Feel free to assign me to this issue if that helps.

**Comment by aireilly** [comment]
Note - repos inside the OpenShift org are Ok. `https://github.com/openshift/*` are fine.

**Comment by apinnick** [comment]
> Note - repos inside the OpenShift org are Ok. `https://github.com/openshift/*` are fine.

I think "owned and maintained by Red Hat" would cover that. Or did you want that URL in the 'valid' list?

**Comment by aireilly** [comment]
I think we need clarification from @kalexand-rh maybe. Are all GitHub links forbidden? Or are GitHub links from inside the [OpenShift](https://github.com/openshift) organization allowed?
