### ISSUE TITLE
"bare metal" pull request #854 might be preventing Vale from running

### ISSUE THREAD

**Issue by emteelb** [redhat-documentation/vale-at-red-hat#856]
Closed pull request  #854 seems to be causing an issue with running the Vale prose linter. Here is an example linting from stdin:

```
$ lbv "bare metal is the way to go"
E201 Invalid value [/vale_app/styles/RedHat/TermsErrors.yml:22:4]:

  21    "(?<!self-)hosted engine|hosted-engine": self-hosted engine
  22*   "bare metal( clusters?| compute| configuration| controls?| environments?| equipment| events?| hardware| hosts?| infrastructure| installations?| installers?| machines?| media| nodes?| provisioning| servers?| workers?)": bare-metal $1
  23    "bare-metal(?! clusters?| compute| configuration| controls?| environments?| equipment| events?| hardware| hosts?| infrastructure| installations?| installers?| machines?| media| nodes?| provisioning| servers?| workers?)": bare metal
  24    "[bB]asic [aA]uth": Basic HTTP authentication|Basic authentication

capture group not supported; use '(?:' instead of '('

Execution stopped with code 1.
```

Here, `lbv` is a local alias for running Vale from a Docker container. I rebuilt this container today after the pull request was committed and got this error. If I take the container's "sync" step back to a locally cached version from before the pull request, the error goes away. The sync step I believe "grabs" packaged style rules. I don't know if that is significant here or not.

Hope this report is helpful and that I have provided enough details. Happy to do more if needed.

**Comment by aireilly** [comment]
Can you give me more information? This error is because you are using an older version of vale in your container.

```
$ podman run quay.io/rhdevdocs/devspaces-documentation vale -v
vale version 3.7.0
```

You need Vale 3.7+

**Comment by aireilly** [comment]
https://github.com/errata-ai/vale/releases/tag/v3.7.0

**Comment by emteelb** [comment]
Ah! Indeed, that is the problem for me. My container was based on an older Vale version (`jdkato/vale:v2.x.x`). Thank you for the reply and apologies for the noise.
